### ISSUE TITLE
Not possible to pyccelise Numpy Where function

### ISSUE THREAD

**Issue by dominikbell** [pyccel/pyccel#1123] opened 2022-06-01 12:01 UTC
There are problems when pyccelising codes that contain the numpy.where function. I have taken from `pyccel/tests/epyccel/recognised_functions/test_numpy_funcs.py` the following function:

```
def get_chosen_elements(arr):

    from numpy import where, shape

    a = where(arr%2, arr, arr+1)
    s = shape(a)

    return len(s), s[0], a[0,0], a[0,1], a[1,0], a[1,1]
```

I can run this function without any problems in python, e.g. with

```
a = numpy.random.rand(3,4)
get_chosen_elements(a)
```

When I try to reproduce the procedure from `pyccel/tests/epyccel/recognised_functions/test_numpy_funcs.py` by calling
```
from pyccel.epyccel import epyccel
```
and then run `epyc_fun = epyccel(get_chosen_elements, language='fortran')` I get the following error message:

```
ERROR at annotation (semantic) stage
pyccel:
 |fatal [semantic]: mod_44dljmex0wql_44dljmex0wql.py [5,8]| Function call cannot be processed. Please ensure that your code runs correctly in python. If this is the case then you may be using function arguments which are not currently supported by pyccel. Please create an issue at https://github.com/pyccel/pyccel/issues and provide a small example of your problem. (where(arr % 2, arr, arr + 1))

Traceback (most recent call last):
  File "/home/ubuntu/Struphy/hylife/pyccel_test.py", line 22, in <module>
    epyc_fun = epyccel(get_chosen_elements, language='fortran')
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyccel/epyccel.py", line 333, in epyccel
    mod, fun = epyccel_seq( python_function_or_module, **kwargs )
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyccel/epyccel.py", line 168, in epyccel_seq
    execute_pyccel(pymod_filename,
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyccel/codegen/pipeline.py", line 246, in execute_pyccel
    raise PyccelSemanticError('Semantic step failed') from None
pyccel.errors.errors.PyccelSemanticError: Semantic step failed
```

When adding a type declarator for the variable __arr__ (both ` : 'float[:,:]'` and ` : 'int[:,:]'` have been tried) a similar error occurs:

```
ERROR at annotation (semantic) stage
pyccel:
 |fatal [semantic]: pyccel_test.py [15,8]| Function call cannot be processed. Please ensure that your code runs correctly in python. If this is the case then you may be using function arguments which are not currently supported by pyccel. Please create an issue at https://github.com/pyccel/pyccel/issues and provide a small example of your problem. (where(arr % 2, arr, arr + 1))
```

**Comment by EmilyBourne** [comment] 2022-06-02 06:24
Duplicate of #770 and #745. This will be fixed by #858 . However #858 cannot be merged yet as it does not preserve the existing behaviour (`np.where` implemented for 1 argument)

**Closed** 2022-06-30 19:06 UTC
Labels: bug, duplicate
