### ISSUE TITLE
Error with exponential symbol (gcc 10.2.0 and gcc 9.3.0)

### ISSUE THREAD

**Issue by imadki** [pyccel/pyccel#933] opened 2021-08-05 05:41 UTC
**Describe the bug**
Import error when using exp from numpy. 
undefined symbol: _ZGVbN2v_exp

**To Reproduce**
Provide code to reproduce the behavior:
```python
from numpy import exp
```

Provide the generated code, or the error message:
```bash/fortran/c
Translated code here
```

**Expected behavior**

**Language**
Please specify which language the python code is translated to (Fortran by default)

**Additional context**

**Comment by EmilyBourne** [comment] 2021-08-05 06:26
I cannot reproduce this bug. Could you please provide more information:
- Minimum Working Example (the code provided contains no functions or statements so it has nothing to generate)
- The exact error/backtrace

I am not clear on whether you are seeing a python error or a compiler error?

Which version of pyccel are you using?

**Comment by EmilyBourne** [comment] 2021-08-05 06:51
Does this error occur when importing a successfully compiled .so file?

**Comment by EmilyBourne** [comment] 2021-08-05 07:06
I cannot reproduce this error with the following file:
```
from numpy import exp

def get_exp():
    return exp(3.0)
```
and translating to Fortran or C with the following compilers:
```
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
GNU Fortran (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

If this is indeed a problem when importing the .so file, please could you run pyccel in verbose mode (`verbose=True` for epyccel, `--verbose` for pyccel) and post the commands used to compile. It seems that the math library is not being correctly linked (`-lm`)

**Comment by imadki** [comment] 2021-08-05 08:04
> Does this error occur when importing a successfully compiled .so file?
Yes.

> I cannot reproduce this bug. Could you please provide more information:
> 
>     * Minimum Working Example (the code provided contains no functions or statements so it has nothing to generate)
def initialisation():                                                                                                                               
    from numpy import exp  
   a = exp(10)
>     * The exact error/backtrace
> 
ImportError: module_tools.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZGVbN2v_exp

> 
> I am not clear on whether you are seeing a python error or a compiler error?
>  
It's python error when I call the .so 
> Which version of pyccel are you using?
1.2.4 (even the older versions gave me the same error)

**Comment by EmilyBourne** [comment] 2021-08-05 08:19
> It's python error when I call the .so

In that case, please could you run pyccel in verbose mode (`verbose=True` for epyccel, `--verbose` for pyccel) and post the commands used to compile. It seems that the math library is not being correctly linked (`-lm`)

**Comment by imadki** [comment] 2021-08-05 10:45
> > It's python error when I call the .so
> 
> In that case, please could you run pyccel in verbose mode (`verbose=True` for epyccel, `--verbose` for pyccel) and post the commands used to compile. It seems that the math library is not being correctly linked (`-lm`)

gfortran -O3 -fPIC -I /home/kissami/GITHUB/manapy_hpc/manapy/manapy/tools/__pyccel__ -c /home/kissami/GITHUB/manapy_hpc/manapy/manapy/tools/__pyccel__/module_tools.f90 -o /home/kissami/GITHUB/manapy_hpc/manapy/manapy/tools/__pyccel__/module_tools.o -J /home/kissami/GITHUB/manapy_hpc/manapy/manapy/tools/__pyccel__
gfortran -O3 -fPIC -I /home/kissami/GITHUB/manapy_hpc/manapy/manapy/tools/__pyccel__ -c bind_c_module_tools.f90 -o /home/kissami/GITHUB/manapy_hpc/manapy/manapy/tools/__pyccel__/bind_c_module_tools.o -J /home/kissami/GITHUB/manapy_hpc/manapy/manapy/tools/__pyccel__
/home/kissami/anaconda3/bin/python /home/kissami/GITHUB/manapy_hpc/manapy/manapy/tools/__pyccel__/setup_module_tools.py build
running build
running build_ext
building 'module_tools' extension
/home/kissami/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/kissami/anaconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/kissami/anaconda3/include -fPIC -I/home/kissami/GITHUB/manapy_hpc/manapy/manapy/tools/__pyccel__ -I/home/kissami/anaconda3/lib/python3.8/site-packages/numpy/core/include -I/home/kissami/anaconda3/include/python3.8 -c module_tools_wrapper.c -o build/temp.linux-x86_64-3.8/module_tools_wrapper.o -O3 -fPIC -I /home/kissami/GITHUB/manapy_hpc/manapy/manapy/tools/__pyccel__
x86_64-conda_cos6-linux-gnu-gcc -pthread -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/kissami/anaconda3/lib -L/home/kissami/anaconda3/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/kissami/anaconda3/lib -L/home/kissami/anaconda3/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/kissami/anaconda3/lib -Wl,-rpath-link,/home/kissami/anaconda3/lib -L/home/kissami/anaconda3/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/kissami/anaconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/kissami/anaconda3/include build/temp.linux-x86_64-3.8/module_tools_wrapper.o /home/kissami/GITHUB/manapy_hpc/manapy/manapy/tools/__pyccel__/bind_c_module_tools.o /home/kissami/GITHUB/manapy_hpc/manapy/manapy/tools/__pyccel__/module_tools.o -L/usr/lib/gcc/x86_64-linux-gnu/9 -lgfortran -o build/lib.linux-x86_64-3.8/module_tools.cpython-38-x86_64-linux-gnu.so

**Comment by EmilyBourne** [comment] 2021-08-05 11:08
The `-lm` command does indeed seem to be missing. Looking [here](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/pipeline.py#L207-L208) it seems that this problem is fixed for C but not for fortran for some reason. I assume that the gfortran library normally includes a certain number of math functions as part of the standard which means that it is not necessary on other systems. Does your test code work if you translate to C? (`language='c'` with epyccel, `--language=c` with pyccel)

There are some changes coming to the compiler soon. One of the changes should mean that the math library is always linked to the library. Could you test the branch `ebourne_compiling` (see PR #928 ) and see if this fixes your problem?

**Comment by imadki** [comment] 2021-08-05 11:15
> The `-lm` command does indeed seem to be missing. Looking [here](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/pipeline.py#L207-L208) it seems that this problem is fixed for C but not for fortran for some reason. I assume that the gfortran library normally includes a certain number of math functions as part of the standard which means that it is not necessary on other systems. Does your test code work if you translate to C? (`language='c'` with epyccel, `--language=c` with pyccel)
> 
> There are some changes coming to the compiler soon. One of the changes should mean that the math library is always linked to the library. Could you test the branch `ebourne_compiling` (see PR #928 ) and see if this fixes your problem?

Yes it's ok. What's the difference between the two branches ?

**Comment by EmilyBourne** [comment] 2021-08-05 11:17
> > The `-lm` command does indeed seem to be missing. Looking [here](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/pipeline.py#L207-L208) it seems that this problem is fixed for C but not for fortran for some reason. I assume that the gfortran library normally includes a certain number of math functions as part of the standard which means that it is not necessary on other systems. Does your test code work if you translate to C? (`language='c'` with epyccel, `--language=c` with pyccel)
> > There are some changes coming to the compiler soon. One of the changes should mean that the math library is always linked to the library. Could you test the branch `ebourne_compiling` (see PR #928 ) and see if this fixes your problem?
> 
> Yes it's ok. What's the difference between the two branches ?

There are lots of differences between the 2. It is a complete overhaul of the compilation step. For details, please see the PR

**Comment by imadki** [comment] 2021-08-05 11:21
> > > The `-lm` command does indeed seem to be missing. Looking [here](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/pipeline.py#L207-L208) it seems that this problem is fixed for C but not for fortran for some reason. I assume that the gfortran library normally includes a certain number of math functions as part of the standard which means that it is not necessary on other systems. Does your test code work if you translate to C? (`language='c'` with epyccel, `--language=c` with pyccel)
> > > There are some changes coming to the compiler soon. One of the changes should mean that the math library is always linked to the library. Could you test the branch `ebourne_compiling` (see PR #928 ) and see if this fixes your problem?
> > 
> > 
> > Yes it's ok. What's the difference between the two branches ?
> 
> There are lots of differences between the 2. It is a complete overhaul of the compilation step. For details, please see the PR

OK thanks Emily. But It'll be important to fix the bug for the last version to take advantage of all updates.

**Comment by EmilyBourne** [comment] 2021-08-05 11:25
> OK thanks Emily. But It'll be important to fix the bug for the last version to take advantage of all updates.

Sorry, I'm not sure what you mean by this. If I understood correctly, the bug will be fixed as soon as the PR is merged. The PR updates the version number so this fix will then be immediately available via pip. We can't apply it retroactively to versions of pyccel which already exist. Maybe we could discuss this on slack if there is some confusion?

**Closed** 2021-08-06 09:47 UTC
Labels: bug
