### ISSUE TITLE
Empty target vector when translating list comprehension to C

### ISSUE THREAD

**Issue by jalalium** [pyccel/pyccel#1957] opened 2024-08-01 10:26 UTC
### Describe the bug
List comprehensions are converted to stc vectors, however these vectors are not initialized and are then accessed.

### To Reproduce
```python
if __name__ == '__main__':
    y = [x**2 for x in range(5)]
 ```

### Error details
Provide the generated code, or the error message:
```c
#include "boo.h"
#include <stdlib.h>
#include <stdint.h>
#ifndef _VEC_INT64_T
#define _VEC_INT64_T
#define i_type vec_int64_t
#define i_key int64_t
#include <stc/vec.h>
#endif // _VEC_INT64_T

int main()
{
    int64_t x;
    vec_int64_t y;
    int64_t Dummy_0000;
    Dummy_0000 = INT64_C(0);
    for (x = INT64_C(0); x < INT64_C(5); x += INT64_C(1))
    {
        (*vec_int64_t_at_mut(&y,Dummy_0000)) = x * x;
        Dummy_0000 = Dummy_0000 + INT64_C(1);
    }
    vec_int64_t_drop(&y);
    return 0;
}
```

### Expected behavior
The vector should reserve the necessary memory before population.

### Language
C

**Comment by EmilyBourne** [comment] 2024-08-01 10:35
Duplicate of #1948?

**Comment by jalalium** [comment] 2024-08-01 10:41
Oops, sorry!

**Closed** 2024-08-01 10:42 UTC
Labels: bug
