### ISSUE TITLE
Allow multiple consecutive `+` and `-` unary operators

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#563] opened 2020-11-26 11:18 UTC
Description
------------
As a USER, I would like to support the Python syntax `x = - - 1` and variations of it.

Language
------------
C, Fortran

Acceptance Criteria
-------------------------
- [x] Simplify consecutive unary operators `+` and  `-`
- [ ] Print parentheses when unary operator is combined with binary operator

**Comment by EmilyBourne** [comment] 2020-11-26 11:22
I cannot reproduce this problem. This works for me, and is correctly translated to:
```
x = - (-1)
```

**Comment by EmilyBourne** [comment] 2020-11-26 11:23
> Print parentheses when unary operator is combined with binary operator

This is fixed in PR #559

**Comment by EmilyBourne** [comment] 2020-11-26 19:03
See #564 for details of the implementation and use case

**Comment by EmilyBourne** [comment] 2020-11-27 07:06
Superseded by issue #564

**Closed by EmilyBourne** 2020-11-27 07:06 UTC
Labels: Language:C, Language:Fortran, bug
