### ISSUE TITLE
the naming of variables with the reserved keywords in c language cause problems in compiling stage 

### ISSUE THREAD

**Issue by rakati** [pyccel/pyccel#402] opened 2020-08-26 11:04 UTC
**Describe the bug**
the naming of variables with the reserved keywords in c language cause problems in the compiling stage.

**The python code**
```python
from pyccel.decorators import types

@types(int)
def simple_function(do):
        twice = do * do
        return twice
```

the c generated code is correct
```c
long simple_function(long do) {
    long twice;
    twice = do * do;
    return twice;
}
``` 
but in the building stage this error occured:
```c
test_wrapper.c:4:27: error: expected ‘;’, ‘,’ or ‘)’ before ‘do’
    4 | long simple_function(long do);
      |                           ^~
test_wrapper.c: In function ‘simple_function_wrapper’:
test_wrapper.c:8:10: error: expected identifier or ‘(’ before ‘do’
    8 |     long do;
      |          ^~
test_wrapper.c:10:39: error: expected expression before ‘do’
   10 |     if (!PyArg_ParseTuple(args, "l", &do))
      |                                       ^~
test_wrapper.c:12:13: warning: implicit declaration of function ‘simple_function’; did you mean ‘simple_function_wrapper’? [-Wimplicit-function-declaration]
   12 |     twice = simple_function(do);
      |             ^~~~~~~~~~~~~~~
      |             simple_function_wrapper
test_wrapper.c:12:29: error: expected expression before ‘do’
   12 |     twice = simple_function(do);
      |                             ^~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1


ERROR at shared library generation stage
Traceback (most recent call last):
  File "/home/rakati/dev/pyccel_v/bin/pyccel", line 11, in <module>
    load_entry_point('pyccel', 'console_scripts', 'pyccel')()
  File "/home/rakati/dev/pyccel/pyccel/commands/console.py", line 235, in pyccel
    execute_pyccel(filename,
  File "/home/rakati/dev/pyccel/pyccel/codegen/pipeline.py", line 263, in execute_pyccel
    sharedlib_filepath = create_shared_library(codegen,
  File "/home/rakati/dev/pyccel/pyccel/codegen/python_wrapper.py", line 192, in create_shared_library
    raise RuntimeError("Failed to build module")
RuntimeError: Failed to build module
```

**Language**
C

**Comment by EmilyBourne** [comment] 2020-08-26 11:06
Duplicate of #227 
This is one of the many naming problems discussed in issue #227

**Closed** 2020-08-26 11:09 UTC
Labels: Language:C, bug
