### ISSUE TITLE
division and floor division operators not work well in c

### ISSUE THREAD

**Issue by rakati** [pyccel/pyccel#407] opened 2020-08-31 13:50 UTC
**Describe the bug**
the code generated for the division operation is not correct
this is the used code
**Test Code**
```python
@types(int, int)
def sample_div(x, y):
        return x / y
```
it generates this in c
```c
double sample_div(long x, long y)
{
    double Out_0001;
    Out_0001 = real(x) / real(y);
    return Out_0001;
}
```
and for the floor division operation
```python
@types(int, int)
def floor_div(x, y):
       return x // y
```
gives this error
```bash
ERROR at code generation stage
pyccel: [codegen]
 |fatal| Pyccel has encountered syntax that has not been implemented yet.
Please create an issue at https://github.com/pyccel/pyccel/issues and provide a small example of your problem.
Do not forget to specify your target language (PyccelFloorDiv(x, y))
```

**Language**
C

**Comment by EmilyBourne** [comment] 2020-08-31 13:55
This is 2 unrelated bugs.
1. Floor division is not implemented.
2. Casting is not correctly implemented (duplicate of #389 )

Do you agree or do you think there is something beyond the casting that doesn't work as expected?
If you agree then can we restrict this issue to bug 1, and leave bug 2 to issue #389?

**Comment by rakati** [comment] 2020-08-31 14:27
yes, the floor division is a feature. 
but the division operator has no relation with python casting in issue #389.
here the casting is added at the generation code stage, not converted from python code.
and by observation, I see that the problem here is the c division printer act like a Fortran division printer.
because this the way casting in Fortran.

**Comment by EmilyBourne** [comment] 2020-08-31 14:33
> here the casting is added at the generation code stage, not converted from python code.

Normally even if casting is added later it should use the same mechanisms as if it had been written in the python code. That way we avoid code duplication in the printer and make it easier to make global modifications (e.g. change the precision `float`<->`double`)

> and by observation, I see that the problem here is the c division printer act like a Fortran division printer.
> because this the way casting in Fortran.

Do you expect casting to work differently in c?
I don't know how @MenoIy has gone about implementing it

**Comment by EmilyBourne** [comment] 2020-08-31 14:38
> and by observation, I see that the problem here is the c division printer act like a Fortran division printer.
Looking at the code, I now see what you mean. The c printer doesn't just act like the fortran printer, it seems that the function `_print_PyccelDiv` has been copied and pasted from Fortran. For both languages the content is:
```
    def _print_PyccelDiv(self, expr):
        args = [self._print(a) for a in expr.args]
        if all(a.dtype is NativeInteger() for a in expr.args):
            return ' / '.join('real({})'.format(self._print(a)) for a in args)
        return  ' / '.join(self._print(a) for a in args)
```
In my opinion neither is correct as neither use the casting classes. This should be done to allow precision decisions to be made easily

**Comment by rakati** [comment] 2020-08-31 14:53
I think I didn't explain well
the problem that @MenoIy mention in issue #389 is about converting the cast in python code to cast in c code.
but in this example there no casting only division operation
```python
@types(int, int)
def sample_div(x, y):
        return x / y
```
the casting should be added in the generating code stage for the division to be correct.
because division in python return real type, in c language dividing two integer number returns an integer number,
to get float number as result we should cast them to float.
here in this example, the printer tries to cast x and y to real in the Fortran way
```c
double sample_div(long x, long y)
{
    double Out_0001;
    Out_0001 = real(x) / real(y);
    return Out_0001;
}
```
in c there is no function 'real' that cast an integer to real.
the casting in c is as follows.
```c
double sample_div(long x, long y)
{
    double Out_0001;
    Out_0001 = (double)(x) / (double)(y);
    return Out_0001;
}
```

**Comment by EmilyBourne** [comment] 2020-08-31 15:05
> the casting should be added in the generating code stage for the division to be correct.

This is exactly right. The casting should be added. Note, in my opinion, it should be **added**, not just printed

From this code:
```
@types(int, int)
def sample_div(x, y):
        return x / y
```

Currently what is generated is:
```
PyccelDiv(Variable('x','int'),Variable('y','int'))
```
However for c (and fortran) what should be generated is:
```
PyccelDiv(PythonFloat(Variable('x','int')),PythonFloat(Variable('y','int')))
```
Currently the translation of the `PythonFloat` object is written locally (and incorrectly in c), and the object itself is not used.

I think the `PythonFloat` object should be added explicitly into the expression in the function `_print_PyccelDiv`
E.g:
```
    def _print_PyccelDiv(self, expr):
        args = [self._print(a) for a in expr.args]
        if all(a.dtype is NativeInteger() for a in expr.args):
            return ' / '.join(self._print(PythonFloat(a)) for a in args)
        return  ' / '.join(self._print(a) for a in args)
```
This means that the code for `PythonFloat` will be written using the same mechanism as for the casting. This has 2 advantages, firstly if for some reason, we decide to use `float` everywhere in the c code instead of `double` then there will a limited number of places where this needs changing. Secondly if the case becomes more complicated then we have avoided code repetition. For example in the case of a floor division we could write very similar code:
```
    def _print_PyccelFloorDiv(self, expr):
        args = [self._print(a) for a in expr.args]
        if any(a.dtype is NativeInteger() for a in expr.args):
            return ' / '.join(self._print(Int(a)) for a in args)
        return  ' / '.join(self._print(a) for a in args)
```
And the function `_print_Int` could decide whether the cast needs printing or not depending on the type of `a`

**Comment by rakati** [comment] 2020-08-31 15:20
yap I agree with you, this method is more accurate instead of using a manually casting in printers.

**Closed** 2020-10-07 07:57 UTC
Labels: Language:C, bug, enhancement
