### ISSUE TITLE
Create option to generate Fortran code with default integers

### ISSUE THREAD

**Issue by Beliavsky** [pyccel/pyccel#604] opened 2020-12-18 16:53 UTC
Python integers are translated to integer(C_LONG_LONG), which are integers with a large range. However, the Fortran code is cluttered with _C_LONG_LONG after all integer constants, which makes it less readable. Could you
(1) add an option where Python integers are mapped to default Fortran integers?
(2) and/or rename C_LONG_LONG with 

`use ISO_C_BINDING, only: i64 => C_LONG_LONG`

and change the generated Fortran code accordingly?

**Comment by saidctb** [comment] 2020-12-18 17:07
agree, we should probably rename  the iso_c_binding types to make them more readable.
 what do you think @yguclu  and @EmilyBourne ?

**Comment by EmilyBourne** [comment] 2020-12-18 17:20
You are right.  This was discussed [here](https://github.com/pyccel/pyccel/issues/487#issuecomment-717852036) but we never created an issue for it so it was forgotten. The main difficulty comes from ensuring that the names are not used by the user's variables. This is linked to issue #227

**Comment by saidctb** [comment] 2020-12-18 20:50
> You are right. This was discussed [here](https://github.com/pyccel/pyccel/issues/487#issuecomment-717852036) but we never created an issue for it so it was forgotten. The main difficulty comes from ensuring that the names are not used by the user's variables. This is linked to issue #227

I think we can use the C types as names, and then we will treat the name claching  the same way in fortran or C

**Comment by yguclu** [comment] 2020-12-21 17:28
As mentioned above, we have discussed about this before. But since this is an "aesthetic" problem it has never reached a high priority... for obvious reasons we try to fix bugs first! 😅 

When we decide to tackle this issue, I think that using the `=>` syntax as suggested by @Beliavsky is the cleanest solution. But first we need to make sure that our treatment of name clashes in the generated code is bullet-proof.

**Comment by yguclu** [comment] 2020-12-21 17:34
As for mapping Python integers to default Fortran integers, in the best-case scenario this adds complications at the Python-Fortran interface. In the worst-case scenario the generated Fortran code will not reproduce the behavior of the original Python code. This is why we are happy with using long integers, a solution which has proven to be solid across multiple platforms.

**Comment by EmilyBourne** [comment] 2021-06-17 12:20
Duplicate of #856

**Closed** 2021-08-24 15:46 UTC
Labels: duplicate, enhancement, Language:Fortran
