### ISSUE TITLE
Comments and OpenMP pragmas are printed in the wrong place

### ISSUE THREAD

**Issue by MenoIy** [pyccel/pyccel#829] opened 2021-03-30 11:45 UTC
Comments and omp pragmas are printer in the wrong place

```python
def func(x : int):
    if x == 0:
        pass
    else:
        # x is not 0
        pass
```

```fortran
subroutine func(x)

  implicit none

  integer(C_INT64_T), value :: x

  if (x == 0_C_INT64_T) then
    ! pass
    !x is not 0
  else
    ! pass
  end if

end subroutine func
```
The same behavior is reproduced when using omp pragmas

**Comment by EmilyBourne** [comment] 2021-03-30 13:17
I think this is caused by [this line](https://github.com/pyccel/pyccel/blob/master/pyccel/parser/extend_tree.py#L173)
I cannot think of an explanation for why the start of the else block needs to be after the first comment that we are inserting. Changing this line to:
```
expr = logical_and(else_no <= comment_lines_no[k-1], else_no<=previous_stmt_body_last_lineno)
```
seems to fix the problem. The same condition is used [here](https://github.com/pyccel/pyccel/blob/master/pyccel/parser/extend_tree.py#L228)

@saidctb  I believe you wrote this bit of code. Do you remember why you added this condition?

**Comment by saidctb** [comment] 2021-03-30 15:11
can you check if the problem is only in the `else` statement and not the `elif` statement, because Python treats them differently.
for the solution, I don't remember anymore, we probably need to add tests by using the python printer and comparing the strings

**Comment by EmilyBourne** [comment] 2021-03-30 15:15
@saidctb 
> can you check if the problem is only in the `else` statement and not the `elif` statement, because Python treats them differently.

The problem is only when there is no `elif` statement. Both of the following are translated correctly:
```
def func(x : int):
    if x == 0:
        pass
    elif x ==2:
        #help
        pass
    else:
        # x is not 0
        pass
```
```
def func(x : int):
    if x == 0:
        pass
    elif x ==2:
        #help
        pass
```

**Comment by EmilyBourne** [comment] 2021-03-30 22:40
I have pushed a fix for this to the branch `devel-issue829`. If you are happy with the result then we can open a PR

**Closed** 2021-05-18 18:32 UTC
Labels: Language:C, Language:Fortran, bug
