### ISSUE TITLE
Numpy.where doesn't work

### ISSUE THREAD

**Issue by MostafaMamouni** [pyccel/pyccel#770] opened 2021-02-24 22:42 UTC
**Describe the bug**
Pyccel fails when using numpy.where in any data type, it might need some investigations.

**To Reproduce**
Provide code to reproduce the behavior:
```python
     @types('int[:]')
    def test_int(arr):
        from numpy import where
        a = where(arr > 5, arr, arr*2)
        return a
```

The error message:
```
TypeError: __init__() takes 2 positional arguments but 4 were given.
```

**Expected behavior**
generate correct Fortran/C code.

**Language**
Fortran

**Additional context**
The tests are already in place in #719.

**Comment by EmilyBourne** [comment] 2021-02-25 08:00
Numpy.where is an elementwise IfTernaryOperator. As such, it does not make much sense to test this with scalars. Can you confirm that the bug exists with array types too?

**Comment by EmilyBourne** [comment] 2021-02-25 08:06
It would also be good to add a `__new__` method to `NumpyWhere` which returns an `IfTernaryOperator` if the `condition` argument is a scalar

**Comment by EmilyBourne** [comment] 2021-02-25 08:08
Have you also tried NumpyWhere with the standard 3 arguments? As explained in the [doc](https://numpy.org/doc/stable/reference/generated/numpy.where.html) passing only 1 argument is non-standard and the function `nonzero` should be preferred. When we have a `NumpyNonZero` I imagine this case should be handled in a `__new__` method. In the mean time perhaps it would be good to raise an error in this case?

**Comment by EmilyBourne** [comment] 2021-03-31 13:49
Is this a duplicate of #745 ?

**Closed** 2022-06-30 19:06 UTC
Labels: bug, Language:Fortran
