### ISSUE TITLE
Pyccelisation of python scalar method `conjugate()`

### ISSUE THREAD

**Issue by tomcaruso** [pyccel/pyccel#1430] opened 2023-07-05 11:42 UTC
### Describe the bug
The `float` python type have a method `.conjugate()`.
When trying to pyccelise a file containing it, pyccel have a fatal error.

### To Reproduce
Try pyccelise this function
```python
def fun(val:'float'):
    return val.conjugate()
```
### Error details
Provide the generated code, or the error message:
```bash/fortran/c
ERROR at annotation (semantic) stage
pyccel:
 |fatal [semantic]: main.py [3,11]| Attribute conjugate not found
```
### Expected behavior
The conjugate method should work on a `float` or pyccel should remove it when it is applied to a `float`.

**Comment by EmilyBourne** [comment] 2023-07-05 11:47
Duplicate of #1429

**Closed** 2023-07-07 10:00 UTC
Labels: bug, duplicate
